affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 4
symbolic.funs_name.0:
- - x
  - x
  - x
  - sin
- - '0'
  - '0'
  - x
  - '0'
symbolic.funs_name.1:
- - '0'
  - x
- - x
  - '0'
- - x
  - x
symbolic_enabled: true
width:
- - 4
  - 0
- - 2
  - 0
- - 3
  - 0
