MODEL:
  TYPE: swinv2
  NAME: simmim_pretrain
  DROP_PATH_RATE: 0.0
  SIMMIM:
    NORM_TARGET:
      ENABLE: True
      PATCH_SIZE: 47
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 6
    PATCH_SIZE: 4
DATA:
  IMG_SIZE: 192
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
  BATCH_SIZE: 1024
  NUM_WORKERS: 24
  DATA_PATH: '../../data/sports'
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 10
  BASE_LR: 1.4e-3
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 5
TAG: simmim_pretrain__swinv2_tiny__img192_window6__800ep