MODEL:
  TYPE: swinv2
  NAME: simmim_train
  PRETRAINED: '../../models/swin2/simmim_large.pth'
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 14
    PATCH_SIZE: 4
DATA:
  IMG_SIZE: 224
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
  BATCH_SIZE: 960
  NUM_WORKERS: 24
  DATA_PATH: '../../data/sports'
TRAIN:
  EPOCHS: 20
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 20