MODEL:
  TYPE: swinv2
  NAME: simmim_train
  PRETRAINED: '../../models/swin2/simmim.pth'
  DROP_PATH_RATE: 0.2
  SIMMIM:
    NORM_TARGET:
      ENABLE: True
      PATCH_SIZE: 47
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    PATCH_SIZE: 4
DATA:
  IMG_SIZE: 224
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
  BATCH_SIZE: 960
  NUM_WORKERS: 24
  DATA_PATH: '../../data/sports'
TRAIN:
  EPOCHS: 20
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-4
  WARMUP_LR: 5e-7
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 5
  LR_SCHEDULER:
    NAME: 'multistep'
    GAMMA: 0.1
    MULTISTEPS: [700,]
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_pretrain__swinv2_tiny__img224_window7__800ep